name: faucomplus
description: angraz.com.br


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 2.1.1+4

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  flutter_barcode_scanner: ^2.0.0-nullsafety.0

  progress_button: ^0.0.1

  carousel_pro: ^0.0.13
  
  http: ^0.13.4

  fluttertoast: ^8.0.7

  day_selector: ^1.0.0

  sqflite: ^2.0.2

  path_provider: ^2.0.2

  cpfcnpj: ^1.0.3

  crypto: ^3.0.1

  intl: ^0.17.0

  flutter_holo_date_picker: ^1.0.1
  mask_text_input_formatter: ^2.4.0 
  flip_card: ^0.6.0

   
  imei: ^0.0.1

  credit_card_type_detector: ^1.1.0


  dropdownfield: ^1.0.3

  cupertino_icons: ^0.1.3

  #Inicio e fim de Promocão
  date_format: ^2.0.2

  macadress_gen: ^0.0.3

  plugin_platform_interface: ^2.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/imagens/
    - assets/imagens/butoes/

  fonts:
     - family: Acme
       fonts:
         - asset: assets/fonts/Acme-Regular.ttf
       #  - asset: fonts/Schyler-Italic.ttf
     - family: Pacifico
       fonts:
         - asset: assets/fonts/Pacifico-Regular.ttf
           weight: 400
     - family: Spicy
       fonts:
         - asset: assets/fonts/SpicyRice-Regular.ttf
           weight: 400
     - family: Dancing
       fonts:
         - asset: assets/fonts/DancingScript-Regular.ttf
           weight: 400
     - family: Titanone
       fonts:
         - asset: assets/fonts/TitanOne-Regular.ttf
           weight: 400
     - family: Lobster
       fonts:
         - asset: assets/fonts/Lobster-Regular.ttf
           weight: 400
